#!/bin/bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging


get_app_info() {
  local OUTPUT_FILE=build_response
  /usr/bin/curl -n https://api.heroku.com/apps/$heroku_app_name \
    -H "Content-Type: application/json" \
    -H "Accept: application/vnd.heroku+json; version=3" \
    -H "Authorization: Bearer $heroku_api_key" > $OUTPUT_FILE

  RELEASED_AT=`jq .released_at $OUTPUT_FILE`
}



source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi
payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

cat $payload
cd $source
heroku_api_key=$(jq -r '.source.heroku_api_key // ""' < $payload)
heroku_app_name=$(jq -r '.source.heroku_app_name // ""' < $payload)

get_app_info

jq -n "{
  version: {
    released_at: $RELEASED_AT
  },
  metadata: []
}" >&3